version: '3'

services:
  web:
    build: ./Backend/
    command: python eurovision/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Backend/code
    ports:
      - "8000:8000"
    networks:
      - "backend"
    env_file:
      - ./Backend/.env.dev

  nginx:
    build: ./NGINX/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    depends_on:
      - web

networks:
  backend: